/*
 * Host-compilable protocol tests.
 *
 * Golden fixtures under fixtures/ are generated by the real soulcloud.js
 * codecs (@msgpack/msgpack), so decode tests verify byte-level compatibility
 * with the backend, and encode tests verify byte-identical output.
 *
 * Build & run: tests/host/build.sh
 */

#include <cstdint>
#include <cstdio>
#include <cstring>
#include <unistd.h>

#include "protocol.hpp"

using namespace soulcloud;

static int g_fail = 0;

#define CHECK(cond, msg)                                            \
    do {                                                            \
        if (cond) {                                                 \
            printf("  ok: %s\n", msg);                              \
        } else {                                                    \
            printf("  FAIL: %s (line %d)\n", msg, __LINE__);        \
            g_fail++;                                               \
        }                                                           \
    } while (0)

static bool load_file(const char *path, uint8_t *buf, size_t cap, size_t *out_len)
{
    FILE *f = fopen(path, "rb");
    if (f == NULL) {
        printf("  FAIL: cannot open %s\n", path);
        g_fail++;
        return false;
    }
    const size_t n = fread(buf, 1, cap, f);
    fclose(f);
    *out_len = n;
    return true;
}

static const uint8_t EXPECTED_ID[16] = {0x00, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77,
                                        0x88, 0x99, 0xaa, 0xbb, 0xcc, 0xdd, 0xee, 0xff};

static void test_topic_helpers()
{
    printf("[topics]\n");
    char t[160];
    topic_cmd_exec(t, sizeof(t), "dev-1");
    CHECK(strcmp(t, "soulcloud/v1/devices/dev-1/cmd/exec") == 0, "cmd/exec topic");
    topic_cmd_result(t, sizeof(t), "dev-1");
    CHECK(strcmp(t, "soulcloud/v1/devices/dev-1/cmd/result") == 0, "cmd/result topic");
    topic_ota(t, sizeof(t), "dev-1");
    CHECK(strcmp(t, "soulcloud/v1/devices/dev-1/ota") == 0, "ota topic");
    topic_ota_result(t, sizeof(t), "dev-1");
    CHECK(strcmp(t, "soulcloud/v1/devices/dev-1/ota/result") == 0, "ota/result topic");
    topic_log(t, sizeof(t), "dev-1");
    CHECK(strcmp(t, "soulcloud/v1/devices/dev-1/log") == 0, "log topic");
    topic_stat(t, sizeof(t), "dev-1");
    CHECK(strcmp(t, "soulcloud/v1/devices/dev-1/stat") == 0, "stat topic");
}

static void test_decode_command_exec()
{
    printf("[decode cmd/exec]\n");
    uint8_t buf[512];
    size_t len = 0;

    // golden fixture: {id: bin16, seq: 1, cmd: "setLogging", args: [{enabled: true}]}
    CHECK(load_file("fixtures/cmd_exec.msgpack", buf, sizeof(buf), &len), "load cmd_exec fixture");
    command_exec ce;
    CHECK(decode_command_exec(buf, len, &ce) == ERR_OK, "decode cmd_exec");
    CHECK(ce.id != NULL && memcmp(ce.id, EXPECTED_ID, 16) == 0, "id bytes");
    CHECK(ce.seq == 1, "seq == 1");
    CHECK(ce.cmd_len == 10 && memcmp(ce.cmd, "setLogging", 10) == 0, "cmd == setLogging");
    CHECK(ce.arg_count == 1, "arg_count == 1");
    CHECK(ce.args[0].key_len == 7 && memcmp(ce.args[0].key, "enabled", 7) == 0, "arg key == enabled");
    CHECK(ce.args[0].value.type == cmd_arg_value::TYPE_BOOL && ce.args[0].value.b, "arg value == true");

    // golden fixture without args: {id, seq: 2, cmd: "reboot", args: nil}
    CHECK(load_file("fixtures/cmd_exec_noargs.msgpack", buf, sizeof(buf), &len), "load noargs fixture");
    CHECK(decode_command_exec(buf, len, &ce) == ERR_OK, "decode noargs");
    CHECK(ce.seq == 2, "seq == 2");
    CHECK(ce.cmd_len == 6 && memcmp(ce.cmd, "reboot", 6) == 0, "cmd == reboot");
    CHECK(ce.arg_count == 0, "arg_count == 0");
}

static void test_decode_command_id()
{
    printf("[decode command id (error-result extraction)]\n");
    uint8_t buf[1024];
    size_t len = 0;
    uint8_t id[16] = {};

    // golden fixture: id is the first key
    CHECK(load_file("fixtures/cmd_exec.msgpack", buf, sizeof(buf), &len), "load cmd_exec fixture");
    CHECK(decode_command_id(buf, len, id) == ERR_OK, "id extracted from golden fixture");
    CHECK(memcmp(id, EXPECTED_ID, 16) == 0, "id bytes match");

    // id in the middle, unknown/other keys before it (skip_value path)
    {
        msgpack_writer w(buf, sizeof(buf));
        w.start_map(3);
        w.write_str("cmd");
        w.write_str("someLongCommandNameThatNobodyUses");
        w.write_str("seq");
        w.write_uint(7);
        w.write_str("id");
        w.write_bin(EXPECTED_ID, 16);
        w.finish_map();
        len = w.bytes_written();
        CHECK(w.finish() == ERR_OK, "write id-last payload");
        CHECK(decode_command_id(buf, len, id) == ERR_OK, "id extracted with other keys first");
        CHECK(memcmp(id, EXPECTED_ID, 16) == 0, "id bytes match");
    }

    // not a map at all
    {
        msgpack_writer w(buf, sizeof(buf));
        w.write_uint(42);
        len = w.bytes_written();
        CHECK(w.finish() == ERR_OK, "write non-map payload");
        CHECK(decode_command_id(buf, len, id) == ERR_BAD_MSG, "non-map rejected");
    }

    // map without an id
    {
        msgpack_writer w(buf, sizeof(buf));
        w.start_map(1);
        w.write_str("cmd");
        w.write_str("reboot");
        w.finish_map();
        len = w.bytes_written();
        CHECK(w.finish() == ERR_OK, "write no-id payload");
        CHECK(decode_command_id(buf, len, id) == ERR_MISSING_FIELD, "missing id reported");
    }

    // id of the wrong type
    {
        msgpack_writer w(buf, sizeof(buf));
        w.start_map(1);
        w.write_str("id");
        w.write_str("notabinary");
        w.finish_map();
        len = w.bytes_written();
        CHECK(w.finish() == ERR_OK, "write str-id payload");
        CHECK(decode_command_id(buf, len, id) == ERR_TYPE, "non-bin id rejected");
    }
}

static void test_encode_command_result()
{
    printf("[encode cmd/result]\n");
    uint8_t out[512];
    size_t out_len = 0;

    command_result cr = {EXPECTED_ID, 1, 0, NULL, 0};
    CHECK(encode_command_result(out, sizeof(out), &out_len, &cr) == ERR_OK, "encode cmd_result");

    // structural verification (the backend accepts any uint width for seq)
    msgpack_reader rd(out, out_len);
    CHECK(rd.expect_map() == 4u, "cmd_result map has 4 fields");
    char key[24];
    size_t key_len = 0;
    const uint8_t *p = NULL;
    uint32_t pl = 0;
    CHECK(rd.read_key(key, sizeof(key), &key_len) == ERR_OK && strcmp(key, "id") == 0, "field id");
    CHECK(rd.read_bin(&p, &pl, 16) == ERR_OK && pl == 16 && memcmp(p, EXPECTED_ID, 16) == 0, "id value");
    CHECK(rd.read_key(key, sizeof(key), &key_len) == ERR_OK && strcmp(key, "seq") == 0, "field seq");
    CHECK(rd.expect_u64() == 1, "seq value");
    CHECK(rd.read_key(key, sizeof(key), &key_len) == ERR_OK && strcmp(key, "code") == 0, "field code");
    CHECK(rd.expect_int() == 0, "code value");
    CHECK(rd.read_key(key, sizeof(key), &key_len) == ERR_OK && strcmp(key, "payload") == 0, "field payload");
    CHECK(rd.peek_type() == mpack_type_nil, "payload nil");
    rd.expect_nil();
    CHECK(rd.finish() == ERR_OK, "cmd_result parse complete");

    // with args payload
    cmd_arg_value v;
    v.type = cmd_arg_value::TYPE_INT;
    v.i = -7;
    cmd_arg arg = {"err", 3, v};
    command_result cr2 = {EXPECTED_ID, 99, -7, &arg, 1};
    CHECK(encode_command_result(out, sizeof(out), &out_len, &cr2) == ERR_OK, "encode cmd_result w/ payload");
    msgpack_reader rd2(out, out_len);
    CHECK(rd2.expect_map() == 4u, "map 4 fields");
    for (uint32_t i = 0; i < 4; ++i) {
        char k[24];
        size_t kl = 0;
        CHECK(rd2.read_key(k, sizeof(k), &kl) == ERR_OK, "read key");
        rd2.skip_value();
    }
    CHECK(rd2.finish() == ERR_OK, "payload variant parse complete");

    // buffer too small -> overflow
    uint8_t tiny[8];
    CHECK(encode_command_result(tiny, sizeof(tiny), &out_len, &cr) == ERR_OVERFLOW, "small buffer overflow");
}

static void test_encode_stat()
{
    printf("[encode stat]\n");
    const uint8_t fw[32] = {};
    memset((void *)fw, 0xab, 32);
    uint8_t out[512];
    size_t out_len = 0;
    device_stat ds = {"SN12345678", 10, fw, 32, 42, "POWERON"};
    CHECK(encode_stat(out, sizeof(out), &out_len, &ds) == ERR_OK, "encode stat");

    msgpack_reader rd(out, out_len);
    CHECK(rd.expect_map() == 4u, "stat map has 4 fields");
    char key[24];
    size_t key_len = 0;
    const uint8_t *p = NULL;
    uint32_t pl = 0;
    const char *s = NULL;
    CHECK(rd.read_key(key, sizeof(key), &key_len) == ERR_OK && strcmp(key, "sn") == 0, "field sn");
    CHECK(rd.read_bin(&p, &pl, 16) == ERR_OK && pl == 10 && memcmp(p, "SN12345678", 10) == 0, "sn value");
    CHECK(rd.read_key(key, sizeof(key), &key_len) == ERR_OK && strcmp(key, "fw") == 0, "field fw");
    CHECK(rd.read_bin(&p, &pl, 32) == ERR_OK && pl == 32, "fw bin len");
    bool fw_ok = true;
    for (uint32_t i = 0; i < 32; ++i) {
        if (p[i] != 0xab) fw_ok = false;
    }
    CHECK(fw_ok, "fw bytes");
    CHECK(rd.read_key(key, sizeof(key), &key_len) == ERR_OK && strcmp(key, "up") == 0, "field up");
    CHECK(rd.expect_u64() == 42, "up value");
    CHECK(rd.read_key(key, sizeof(key), &key_len) == ERR_OK && strcmp(key, "rst") == 0, "field rst");
    // read_str is in-place (no NUL terminator): compare by length, not strcmp
    CHECK(rd.read_str(&s, &pl, 32) == ERR_OK && pl == 7 && memcmp(s, "POWERON", 7) == 0, "rst value");
    CHECK(rd.finish() == ERR_OK, "stat parse complete");
}

static void test_decode_ota_notice()
{
    printf("[decode ota notice]\n");
    uint8_t buf[1024];
    size_t len = 0;
    CHECK(load_file("fixtures/ota_notice.msgpack", buf, sizeof(buf), &len), "load ota notice fixture");

    ota_notice n;
    CHECK(decode_ota_notice(buf, len, &n) == ERR_OK, "decode ota notice");
    CHECK(strcmp(n.release_id, "11111111-2222-3333-4444-555555555555") == 0, "release_id");
    CHECK(strcmp(n.job_id, "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee") == 0, "job_id");
    CHECK(strcmp(n.bin_sha256, "6464646464646464646464646464646464646464646464646464646464646464") == 0, "bin_sha256");
    CHECK(n.bin_size == 123456, "bin_size");
    CHECK(strcmp(n.download_url, "/v1/firmware-releases/11111111-2222-3333-4444-555555555555/bin") == 0, "download url");
    CHECK(strcmp(n.download_token, "eyJhbGciOiJIUzI1NiJ9.payload.sig") == 0, "download token");
    CHECK(strcmp(n.download_expires_at, "2026-08-05T09:30:00.000Z") == 0, "expires_at");
    CHECK(n.has_version && strcmp(n.version, "v2.0.0") == 0, "version");
}

static void test_encode_ota_result()
{
    printf("[encode ota/result]\n");
    uint8_t out[1024];
    size_t out_len = 0;

    // without message: exactly 4 fields (backend rejects null message)
    ota_result r1 = {"11111111-2222-3333-4444-555555555555", "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee", "downloaded", 0, NULL};
    CHECK(encode_ota_result(out, sizeof(out), &out_len, &r1) == ERR_OK, "encode ota/result (no message)");

    msgpack_reader rd(out, out_len);
    CHECK(rd.expect_map() == 4u, "ota/result map has 4 fields");
    char key[24];
    size_t key_len = 0;
    CHECK(rd.read_key(key, sizeof(key), &key_len) == ERR_OK && strcmp(key, "release_id") == 0, "field release_id");
    const char *s = NULL;
    uint32_t slen = 0;
    CHECK(rd.read_str(&s, &slen, 64) == ERR_OK && slen == 36, "release_id value");
    CHECK(rd.read_key(key, sizeof(key), &key_len) == ERR_OK && strcmp(key, "job_id") == 0, "field job_id");
    CHECK(rd.read_str(&s, &slen, 64) == ERR_OK && slen == 36, "job_id value");
    CHECK(rd.read_key(key, sizeof(key), &key_len) == ERR_OK && strcmp(key, "state") == 0, "field state");
    CHECK(rd.read_str(&s, &slen, 16) == ERR_OK && memcmp(s, "downloaded", 10) == 0, "state value");
    CHECK(rd.read_key(key, sizeof(key), &key_len) == ERR_OK && strcmp(key, "code") == 0, "field code");
    CHECK(rd.expect_int() == 0, "code value");
    CHECK(rd.finish() == ERR_OK, "ota/result parse complete");

    // with message: 5 fields
    ota_result r2 = {r1.release_id, r1.job_id, "failed", -2, "checksum mismatch"};
    CHECK(encode_ota_result(out, sizeof(out), &out_len, &r2) == ERR_OK, "encode ota/result (message)");
    msgpack_reader rd2(out, out_len);
    CHECK(rd2.expect_map() == 5u, "ota/result map has 5 fields");
    for (uint32_t i = 0; i < 5; ++i) {
        char k[24];
        size_t kl = 0;
        CHECK(rd2.read_key(k, sizeof(k), &kl) == ERR_OK, "read key");
        rd2.skip_value();
    }
    CHECK(rd2.finish() == ERR_OK, "5-field parse complete");
}

static void test_negative_paths()
{
    printf("[negative paths]\n");
    uint8_t buf[1024];
    size_t len = 0;

    // duplicate "id" key
    {
        msgpack_writer w(buf, sizeof(buf));
        w.start_map(3);
        w.write_str("id");
        w.write_bin(EXPECTED_ID, 16);
        w.write_str("id");
        w.write_bin(EXPECTED_ID, 16);
        w.write_str("seq");
        w.write_uint(1);
        w.finish_map();
        len = w.bytes_written();
        CHECK(w.finish() == ERR_OK, "write dup-key payload");
        command_exec ce;
        CHECK(decode_command_exec(buf, len, &ce) == ERR_DUP_KEY, "duplicate id rejected");
    }

    // missing required field (no seq)
    {
        msgpack_writer w(buf, sizeof(buf));
        w.start_map(2);
        w.write_str("id");
        w.write_bin(EXPECTED_ID, 16);
        w.write_str("cmd");
        w.write_str("reboot");
        w.finish_map();
        len = w.bytes_written();
        w.finish();
        command_exec ce;
        CHECK(decode_command_exec(buf, len, &ce) == ERR_MISSING_FIELD, "missing seq rejected");
    }

    // id wrong length
    {
        msgpack_writer w(buf, sizeof(buf));
        w.start_map(3);
        w.write_str("id");
        w.write_bin(EXPECTED_ID, 8);
        w.write_str("seq");
        w.write_uint(1);
        w.write_str("cmd");
        w.write_str("reboot");
        w.finish_map();
        len = w.bytes_written();
        w.finish();
        command_exec ce;
        CHECK(decode_command_exec(buf, len, &ce) == ERR_FIELD_LEN, "short id rejected");
    }

    // trailing garbage
    {
        msgpack_writer w(buf, sizeof(buf));
        w.start_map(3);
        w.write_str("id");
        w.write_bin(EXPECTED_ID, 16);
        w.write_str("seq");
        w.write_uint(1);
        w.write_str("cmd");
        w.write_str("reboot");
        w.finish_map();
        len = w.bytes_written();
        w.finish();
        buf[len++] = 0x00;  // stray nil byte
        command_exec ce;
        CHECK(decode_command_exec(buf, len, &ce) == ERR_BAD_MSG, "trailing bytes rejected");
    }

    // unknown field is skipped
    {
        msgpack_writer w(buf, sizeof(buf));
        w.start_map(4);
        w.write_str("id");
        w.write_bin(EXPECTED_ID, 16);
        w.write_str("seq");
        w.write_uint(1);
        w.write_str("cmd");
        w.write_str("reboot");
        w.write_str("future_field");
        w.write_int(123);
        w.finish_map();
        len = w.bytes_written();
        w.finish();
        command_exec ce;
        CHECK(decode_command_exec(buf, len, &ce) == ERR_OK, "unknown field skipped");
        CHECK(ce.arg_count == 0, "no args after skip");
    }

    // args with wrong type (int instead of array/nil)
    {
        msgpack_writer w(buf, sizeof(buf));
        w.start_map(4);
        w.write_str("id");
        w.write_bin(EXPECTED_ID, 16);
        w.write_str("seq");
        w.write_uint(1);
        w.write_str("cmd");
        w.write_str("reboot");
        w.write_str("args");
        w.write_int(42);
        w.finish_map();
        len = w.bytes_written();
        w.finish();
        command_exec ce;
        CHECK(decode_command_exec(buf, len, &ce) == ERR_TYPE, "bad args type rejected");
    }

    // not a map at all
    {
        msgpack_writer w(buf, sizeof(buf));
        w.write_uint(7);
        len = w.bytes_written();
        w.finish();
        command_exec ce;
        CHECK(decode_command_exec(buf, len, &ce) == ERR_BAD_MSG, "non-map payload rejected");
    }

    // ota notice missing download.url
    {
        msgpack_writer w(buf, sizeof(buf));
        w.start_map(5);
        w.write_str("release_id");
        w.write_str("11111111-2222-3333-4444-555555555555");
        w.write_str("job_id");
        w.write_str("aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee");
        w.write_str("bin_sha256");
        w.write_str("6464646464646464646464646464646464646464646464646464646464646464");
        w.write_str("bin_size");
        w.write_uint(100);
        w.write_str("download");
        w.start_map(1);
        w.write_str("token");
        w.write_str("tok");
        w.finish_map();
        w.finish_map();
        len = w.bytes_written();
        w.finish();
        ota_notice n;
        CHECK(decode_ota_notice(buf, len, &n) == ERR_MISSING_FIELD, "ota notice without url rejected");
    }

    // ota notice with unknown top-level field and no version
    {
        msgpack_writer w(buf, sizeof(buf));
        w.start_map(6);
        w.write_str("release_id");
        w.write_str("11111111-2222-3333-4444-555555555555");
        w.write_str("job_id");
        w.write_str("aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee");
        w.write_str("bin_sha256");
        w.write_str("6464646464646464646464646464646464646464646464646464646464646464");
        w.write_str("bin_size");
        w.write_uint(100);
        w.write_str("download");
        w.start_map(3);
        w.write_str("url");
        w.write_str("/v1/firmware-releases/x/bin");
        w.write_str("token");
        w.write_str("tok");
        w.write_str("expires_at");
        w.write_str("2026-08-05T00:00:00.000Z");
        w.finish_map();
        w.write_str("future");
        w.write_str("x");
        w.finish_map();
        len = w.bytes_written();
        w.finish();
        ota_notice n;
        CHECK(decode_ota_notice(buf, len, &n) == ERR_OK, "ota notice w/ unknown field ok");
        CHECK(!n.has_version, "version absent");
    }
}

int main(int argc, char **argv)
{
    if (argc > 1) {
        if (chdir(argv[1]) != 0) {
            printf("cannot chdir to %s\n", argv[1]);
            return 2;
        }
    }
    test_topic_helpers();
    test_decode_command_exec();
    test_decode_command_id();
    test_encode_command_result();
    test_encode_stat();
    test_decode_ota_notice();
    test_encode_ota_result();
    test_negative_paths();

    if (g_fail == 0) {
        printf("\nALL TESTS PASSED\n");
        return 0;
    }
    printf("\n%d CHECK(S) FAILED\n", g_fail);
    return 1;
}
